config/routes.rb
BackofficeCore::Engine.routes.draw do
  match 'select_cities/:city_title' => 'cities#select_cities', as: 'select_cities'
  
  resources :companies, only: [:show, :destroy]
  controller :companies do
    get 'company_structure' => :company_structure
    put 'company_structure' => :company_structure_update
    get 'company_details' => :company_details
    put 'company_details' => :company_details_update
    get 'company_employee_posts' => :company_employee_posts
    put 'company_employee_posts' => :company_employee_posts_update
    get 'company_users' => :company_users
    put 'company_users' => :company_users_update
    get 'company_finish' => :company_finish
    put 'company_finish' => :company_finish_update
  end
  match 'company_details/:company_id' => 'companies#company_details', as: 'specific_company_details'
  match 'company_users/:company_id' => 'companies#company_users', as: 'specific_company_users'
  match 'create_company/:parent_company_id' => 'companies#create', as: 'create_company'
  match 'return_company_users/:company_id' => 'companies#return_company_users', as: 'return_company_users'
  
  resource :contact_emails
  resource :contact_phones
  
  resources :groups, except: :show
  
  match 'employee_post/:id' => 'employee_posts#destroy', as: 'employee_post', via: :delete

  controller :passwords do
    get 'request_password' => :request_password
    put 'password' => :set_token
    post 'password' => :create
  end
  match 'password/:token' => 'passwords#new', as: 'password_token'
  
  controller :settings do
    get 'settings' => :index
  end
  
  controller :sessions do
    get 'sign_in' => :new
    post 'sign_in' => :create
    delete 'sign_out' => :destroy
  end

  resources :users
  controller :users do
    put 'forward_roles' => :forward_roles_update
    get 'change_password' => :change_password
    put 'change_password' => :change_password_update
  end
  match 'activate_user/:code' => 'users#activate', as: 'activate_user'
  match 'forward_roles' => 'users#forward_roles', as: 'forward_roles'
  
  root to: "sessions#new"
end

app/models/backoffice_core/ability.rb
#!/bin/env ruby
# encoding: utf-8

module BackofficeCore
  class Ability
    include CanCan::Ability
    
    def initialize(user)
      if user.role? :manage_users
        can :read, User
        can :update, User
      end
      if user.role? :delete_users
        can :destroy, User
      end
      if user.role? :company_founder
        can :manage, Company, id: user.company.tree.ids
      end

      # admins can update group      
      can [:update, :edit], Group, admins: { id: user.id }      
      can :destroy, Group, admin_destroy_group: true, admins: { id: user.id }
      can :add_members, Group, admin_add_user: true, admins: { id: user.id }
      can :remove_members, Group, admin_remove_user: true, admins: { id: user.id }
      # group main admin can do everything
      can [:manage, :add_members, :remove_members, :add_admins, :remove_admins], Group, main_admin_user_id: user.id      
#      can :add_members, Group, main_admin_user_id: user.id
#      can :remove_members, Group, main_admin_user_id: user.id
#      can :remove_admins, Group, main_admin_user_id: user.id
#      can :add_admins, Group, main_admin_user_id: user.id
    end
  end
end

app/models/backoffice_core/city.rb
module BackofficeCore
  class City < ActiveRecord::Base
    attr_accessible :title
  end
end

app/models/backoffice_core/company.rb
#!/bin/env ruby
# encoding: utf-8

module BackofficeCore
  class Company < ActiveRecord::Base
    attr_accessible :id, :parent_company_id, :title, :ico, :dic,
                    :street, :orientation_number, :house_number, :city, :postal_code,
                    :phone, :cell_phone, :fax, :email, :www,
                    :fb, :icq, :skype, :description, :company_type_id,
                    :country_id, :parent_company_id
                    
    validates_presence_of :title, on: :update, message: "nesmí být prázdný"
    
    belongs_to :company_type
    belongs_to :country
    belongs_to :parent_company, class_name: "Company", foreign_key: "parent_company_id"
    has_many :children_companies, class_name: "Company", foreign_key: "parent_company_id"
    has_many :company_detail_types
    has_many :company_details
    has_many :employee_posts
    has_many :users
    has_one :group, foreign_key: "automatic_company_id"

    # counts bill for one company    
    def bill_for_all_company_licenses
      bill = 0
      
      License.all.each do |l|
        bill += self.count_company_licenses(l) * l.price
      end
      bill
    end
    
    # counts complete bill for top company and subcompanies
    def bill_for_whole_company_licenses
      bill = 0
      
      self.tree.one_level_array.each do |c|
        bill += c.bill_for_all_company_licenses
      end
      bill
    end
    
    def branch_office_title
      if self.is_top_parent?
        "Mateřská kancelář"
      else
        self.title
      end
    end    
    
    def children_companies_hash(parent_company)
      hash = {}
      
      if parent_company.children_companies.any?
        parent_company.children_companies.each do |child|
          hash[child.to_s] = self.children_companies_hash(child)
        end
      end
      hash
    end
    
    def count_all_subcompanies
      self.tree.one_level_array.size - 1
    end

    def count_company_licenses(license)
      counter = 0
      
      self.users.each do |u|
        counter += 1 if u.license == license
      end
      counter
    end
    
    def count_indirect_subcompanies
      self.count_all_subcompanies - self.children_companies.count
    end
    
    def count_paid_users_licenses
      licenses_count = 0
      
      self.users.each do |u|
        licenses_count += 1 if u.license.price > 0
      end
      licenses_count
    end

    def count_whole_company_users
      count = 0
      
      self.tree.one_level_array.each do |i|
        count += i.users.count
      end
      count
    end
    
    def count_company_founders
      count = 0
      
      self.users.each do |u|
        count += 1 if u.role?('company_founder')
      end
      count
    end

    def is_child_of?(company)
      ct = CompanyTree.new(company)        
      ct.ids.include? self.id
    end
    
    def is_top_parent?
      self.parent_company.blank?
    end
    
    def primary_post
      self.employee_posts.where("primary_post = 1").first || self.top_parent_company.employee_posts.where("primary_post = 1").first || self.top_parent_company.employee_posts.first
    end
    
    # company_details: key, value = company_detail.id, detail_value
    # recursive: array of company_detail.ids (from first param)
    #            that should be saved in all subcompanies
    def save_existing_company_details(company_details, recursive)
      company_details.each do |key, value|
        # if recursive, pass to all subcompanies
        if recursive.is_a? Hash and recursive.key? key
          detail_title = self.company_details.find(key).company_detail_type.title
          
          self.tree.one_level_array.each do |company|
            cdt = company.company_detail_types.find_by_title(detail_title)
            
            # if chosen detail type doesn't exist, create it and create it's value
            if cdt.blank?
              cdt = company.company_detail_types.create(title: detail_title)
              cdt.company_details.create(detail_value: value, company_id: company.id)
            else # cdt existuje, smazeme dosavadni cd a nastavime nove
              cd = company.company_details.where(company_detail_type_id: cdt.id).first
              
              if cd.blank?
                cdt.company_details.create(detail_value: value, company_id: company.id)
              else
                cd.update_attribute('detail_value', value)
              end
            end
          end
        else
          cd = self.company_details.find(key)
          cd.update_attribute('detail_value', value)
        end
      end
    end

    # saves existing details only in chosen company, not into subcompanies
    def save_existing_company_details_only_node(company_details)
      company_details.each do |key, value|
        cd = self.company_details.find(key)
        cd.update_attribute('detail_value', value)
      end
    end

    # nepropise se novy detail do podpobocek
    def save_new_company_details(new_company_details, recursive)
      x = {}
      new_company_details.each do |key, detail|
          cdt = self.company_detail_types.find_by_title(detail[:title])

          if cdt.blank?
            cdt = self.company_detail_types.create(title: detail[:title])
          end
          
          cd = self.company_details.create(company_detail_type_id: cdt.id, detail_value: detail[:detail_value])
          
          if recursive.is_a? Hash and recursive.key? key
            self.save_existing_company_details({ cd.id => cd.detail_value },
                                               { cd.id => "1" })
          end
          
      end
    end
    
    def save_params_to_all_subcompanies(params, company_params)
      if params.present? and params.any? and self.tree.one_level_array.any?
        params.each do |param, value|
          self.tree.one_level_array.each do |company|
            # rozdil mezi company[:title] a company['title'] - ten druhy vytvarim, potrebuju ale ten druhy
            raise ActiveRecord::RecordInvalid unless company.update_attribute(param, company_params[param])
          end
        end
      end
    end
    
    def to_s
      self.title
    end

    def top_parent_company
      if self.parent_company.blank?
        self
      else
        self.find_top_parent_company(self.parent_company)      
      end
    end
    
    def tree
      CompanyTree.new(self)
    end
    
    def whole_company_users
      users = []
      
      self.tree.one_level_array.each do |company|
        company.users.each do |u|
          users << u
        end
      end
      users
    end
    
    def whole_company_users_count_by_posts
      posts = []
      
      self.employee_posts.each do |post|
        posts << [post.title, post.users.count]
      end
      posts
    end
    
    def manage_automatic_group(main_admin_user)
      if self.group.blank?
        automatic_group = Group.create(title: self.title, 
                            description: 'automatická skupina společnosti', 
                            main_admin_user_id: main_admin_user.id.to_s, 
                            automatic: 1, 
                            automatic_company_id: self.id.to_s, 
                            created_at: Time.now)
      else
        automatic_group = self.group
        automatic_group.update_attribute('title', self.title)
      end
      automatic_group.save!
    end   

    protected

    def find_top_parent_company(company)
      if company.parent_company.present?
        self.find_top_parent_company(company.parent_company)
      else
        company
      end
    end 
  end
end

app/models/backoffice_core/company_detail.rb
module BackofficeCore
  class CompanyDetail < ActiveRecord::Base
    attr_accessible :id, :company_detail_type_id, :company_id, :detail_value
    
    validates_presence_of :company_detail_type_id
    
    belongs_to :company
    belongs_to :company_detail_type
    
    def to_s
      self.id.to_s + ': ' + self.detail_value
    end
  end
end

app/models/backoffice_core/company_detail_type.rb
module BackofficeCore
  class CompanyDetailType < ActiveRecord::Base
    attr_accessible :title, :company_id, :id
    
    validates_presence_of :title
    validates_uniqueness_of :title, scope: :company_id
    
    belongs_to :company
    has_many :company_details
  end
end

app/models/backoffice_core/company_tree.rb
#!/bin/env ruby
# encoding: utf-8

module BackofficeCore
  class CompanyTree
    include ActiveModel::Validations
    include ActiveModel::Conversion
    extend ActiveModel::Naming
    
    attr_accessor :company, :ids, :one_level_array
    
    def initialize(company)
      if company.is_a? Company
        self.company = company
      elsif company.is_a? Integer
        self.company = Company.find(company)
      end
      self.one_level_array = []
      self.one_level_array << self.company
      self.ids = []
      self.ids << self.company.id
      self.list(self.company)
    end
    
    def list(parent_company)
      if parent_company.children_companies.any?        
        parent_company.children_companies.each do |child|
          self.one_level_array << child
          self.ids << child.id
          self.list(child)
        end
      end
    end
  end
end

app/models/backoffice_core/company_type.rb
module BackofficeCore
  class CompanyType < ActiveRecord::Base
    attr_accessible :title
    
    has_many :companies
  end
end

app/models/backoffice_core/contact_email.rb
#!/bin/env ruby
# encoding: utf-8

module BackofficeCore
  class ContactEmail < ActiveRecord::Base
    attr_accessible :id, :email, :email_usage, :note, :primary_email, :user_id
    
    validates_uniqueness_of :email, scope: :user_id, message: 'Tento email již je v databázi uložen.'
    
    belongs_to :user
    
    def to_s
      self.email
    end
  end
end

app/models/backoffice_core/contact_phone.rb
#!/bin/env ruby
# encoding: utf-8

module BackofficeCore
  class ContactPhone < ActiveRecord::Base
    attr_accessible :phone, :phone_type, :phone_usage, :note, :primary_phone, :user_id
    
    validates_uniqueness_of :phone, scope: :user_id, message: 'Tento telefon již je v databázi uložen'
    
    belongs_to :user
    
    def to_s
      self.phone
    end
  end
end

app/models/backoffice_core/country.rb
module BackofficeCore
  class Country < ActiveRecord::Base
    attr_accessible :title
    
    has_many :users
    has_many :companies
  end
end

app/models/backoffice_core/employee_post.rb
module BackofficeCore
  class EmployeePost < ActiveRecord::Base
    attr_accessible :company_id, :title, :primary_post
    
    has_many :users
    belongs_to :company
  end
end

app/models/backoffice_core/language.rb
module BackofficeCore
  class Language < ActiveRecord::Base
    attr_accessible :title
    
    has_and_belongs_to_many :users, join_table: :backoffice_core_languages_users
  end
end

app/models/backoffice_core/license.rb
module BackofficeCore
  class License < ActiveRecord::Base
    attr_accessible :id, :duration, :price, :title, :license_type
    
    has_many :users
    has_and_belongs_to_many :roles, join_table: :backoffice_core_licenses_roles
    
    def to_s
      '<License: ' + self.license_type + ' (license_id: ' + self.id.to_s + ')>'
    end
    
    def paid_licenses
      self.where("price > 0")
    end
  end
end

app/models/backoffice_core/log.rb
module BackofficeCore
  class Log < ActiveRecord::Base
    attr_accessible :description, :title, :user_id, :created_at
    
    belongs_to :user
    
    def to_s
      self.created_at.strftime("%d. %-m. %Y %k:%M:%S").to_s + ' ' + title
    end
  end
end

app/models/backoffice_core/nationality.rb
module BackofficeCore
  class Nationality < ActiveRecord::Base
    attr_accessible :title
    
    has_many :users
  end
end

app/models/backoffice_core/role.rb
module BackofficeCore
  class Role < ActiveRecord::Base
    attr_accessible :id, :name, :role_type
    attr_accessible :license_ids
    
    has_and_belongs_to_many :users, join_table: :backoffice_core_roles_users
    has_and_belongs_to_many :licenses, join_table: :backoffice_core_licenses_roles
    # k dane roli musi mit vyplnene urcite udaje
  end
end

app/models/backoffice_core/user_registration.rb
module BackofficeCore
  class UserRegistration < ActiveRecord::Base
    attr_accessible :id, :title
    
    has_many :users
  end
end

app/controllers/backoffice_core/application_controller.rb
#!/bin/env ruby
# encoding: utf-8

module BackofficeCore
  class ApplicationController < ActionController::Base
    before_filter :current_user, :authorize, :set_mailer_host

    rescue_from CanCan::AccessDenied do |exception|
      flash[:error] = "Nemáte oprávnění."
      redirect_to :back
    end
    
    protected
  
    def authorize
      unless User.find_by_id(session[:user_id])
        redirect_to sign_in_url, alert: "Prosím přihlašte se. Pokud nemáte uživatelský účet, zaregistrujte se."
      end
    end
    
    # workaround for use CanCan in engine
    def current_ability
      BackofficeCore::Ability.new(current_user)
    end
    
    def current_user
      if session[:user_id]
        @current_user = User.find(session[:user_id])
      else
        @current_user = User.new # have to create new empty object
      end
    end
    
    def set_mailer_host
      ActionMailer::Base.default_url_options = { host: request.host_with_port }
    end
  end
end

app/views/backoffice_core/groups/_form.html.erb
      <%= form.submit 'Uložit', class: 'f-right' %>
      <%= link_to 'Smazat skupinu', group_path(@group), { method: :delete, confirm: "Opravdu chcete smazat tuto skupinu?", class: "form-link" } if controller.action_name == "edit" and can? :destroy, @group %>
      <%= hidden_field_tag 'group[main_admin_user_id]', @current_user.id.to_s if controller.action_name == "new" or controller.action_name == "create" %>
      <div class="cleaner"></div>
      
      <% if @group.errors.any? %>
        <p>Opravte chybné zadání.</p>
      <% end %>
      <div class="w215 f-left">
        <%= form.label :title, 'Název nové skupiny:' %><br>
        <% if @group.errors[:title].any? %>
          <%= error_message_on @group, :title %>
        <% end %>
        <%= form.text_field :title %><br><br>
        
        <%= form.label :description, 'Popis skupiny:' %><br>
        <%= form.text_area :description, class: 'w200 h100' %><br><br>
        
        <%= label_tag 'companies', 'Přidat uživatele do skupiny manuálně:' %><br>
        <%= select_tag 'companies', options_for_select(@companies_for_select) %><br>
        
        <%= select_tag 'users_for_membership', options_for_select(@users_for_membership) %><br>
        <a id="add_to_group" class="active_link">Přidat</a><br><br>
        
        <%= label_tag 'members', 'Vybraní uživatelé:' %>
        <% if can? :remove_members, @group %>
          <a id="remove_member" class="active_link">x</a>
        <% end %>
        <br>
        <%= select_tag 'members', options_for_select(@members), { multiple: true, size: 10, id: 'members' } %>
      </div>
      <div class="w215 f-left ml15">
        <% if controller.action_name == 'new' or controller.action_name == 'create' or  @group.is_main_admin? @current_user %>
          <%= label_tag 'Přidat správce do skupiny' %>:<br>
          <%= label_tag 'Vybraní uživatelé' %><br>
          <%= select_tag 'users_for_admin', options_for_select(@users_for_admin), multiple: true, size: 8, class: 'f-left w75' %>
          <p class="f-left w50 t-center">
            <a id="remove_admin" class="active_link">&laquo;</a><br>
            <a id="add_admin" class="active_link">&raquo;</a>
          </p>
          <%= select_tag 'admins', options_for_select(@admins), { multiple: true, size: 8, id: 'admins', class: 'f-left w75' } %>
          <div class="cleaner"></div>
          <hr>
          <%= form.label :admin_add_user, 'Správci skupiny jsou oprávněni k' %>:<br>
          <%= form.check_box :admin_add_user %>
          <%= form.label :admin_add_user, 'Přidat uživatele skupiny' %><br>
          <%= form.check_box :admin_remove_user %>
          <%= form.label :admin_remove_user, 'Odebrat uživatele ze skupiny' %><br>
          <%= form.check_box :admin_destroy_group %>
          <%= form.label :admin_destroy_group, 'Smazat skupinu' %>
        <% end %>
      </div>
      <div class="w400 f-left red"></div>

app/views/backoffice_core/groups/edit.html.erb
<h1>Skupiny</h1>
<%= render partial: '/backoffice_core/flash_messages' %>
  
<div id="left">
  <%= render partial: '/backoffice_core/menu_settings' %>
</div>
<div id="right">
  <div class="ml15">
    <h2>Nastavení skupiny</h2>
    <%= form_for @group do |form| %>
      <%= render partial: '/backoffice_core/groups/form', object: form %>
    <% end %>
  </div>
</div>
<div class="cleaner"></div>

app/views/backoffice_core/groups/index.html.erb
<h1>Skupiny</h1>
<%= render partial: '/backoffice_core/flash_messages' %>
  
<div id="left">
  <%= render partial: '/backoffice_core/menu_settings' %>
</div>
<div id="right">
  <div class="ml15">
    <h2>Správa skupin</h2>
    <% @groups.each do |g| %>
      <div class="group">
        <header>
          <p class="f-left"><strong>
            <%if can? :edit, g %>
              <%= link_to g.title, edit_group_path(g.id) %>
            <% else %>
              <%= g.title %>
            <% end %>
            </strong></p>
          <p class="f-left"><strong><%= g.members.count %> uživatelů</strong></p>
          <p class="f-left">založeno: <%= g.created_at.strftime("%-d. %-m. %Y") %></p>
          <p class="f-left"><%= 'automatická skupina' if g.automatic? %></p>
          <p class="f-left"><strong>X</strong> použitých pravidel</p>
          <p class="f-left main_admin">Hl.správce: <strong><%= g.main_admin ? g.main_admin.whole_name : "žádný" %></strong></p>
          
          <div class="cleaner"></div>
        </header>
        <div class="body">
          <p class="w250 f-left"><%= g.description %></p>
          <div class="w250 f-left">
            <h3>Uživatelé</h3>
            <p>Současný počet uživatelů:&nbsp;<%= g.members.count %></p>
            <p>Průměrný počet uživatelů: jak implementovat?</p>
            <p>Nejnovější uživatel: <%= g.last_member.present? ? g.last_member.whole_name : "žádný" %></p>
            <p>Správců skupiny: <%= g.admins.count %></p>
          </div>
          <div class="cleaner"></div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="cleaner"></div>

app/views/backoffice_core/groups/new.html.erb
<h1>Skupiny</h1>
<%= render partial: '/backoffice_core/flash_messages' %>

<div id="left">
  <%= render partial: '/backoffice_core/menu_settings' %>
</div>
<div id="right">
  <div class="ml15">
    <h2>Nová skupina</h2>

    <%= form_for(@group, url: groups_url, method: :post) do |form| %>
      <%= render partial: '/backoffice_core/groups/form', object: form %>
    <% end %>
  </div>
</div>
<div class="cleaner"></div>