config/routes.rb
BackofficeCore::Engine.routes.draw do
  match 'select_cities/:city_title' => 'cities#select_cities', as: 'select_cities'
  
  resources :companies, only: [:show, :destroy]
  controller :companies do
    get 'company_structure' => :company_structure
    put 'company_structure' => :company_structure_update
    get 'company_details' => :company_details
    put 'company_details' => :company_details_update
    get 'company_employee_posts' => :company_employee_posts
    put 'company_employee_posts' => :company_employee_posts_update
    get 'company_users' => :company_users
    put 'company_users' => :company_users_update
    get 'company_finish' => :company_finish
    put 'company_finish' => :company_finish_update
  end
  match 'company_details/:company_id' => 'companies#company_details', as: 'specific_company_details'
  match 'company_users/:company_id' => 'companies#company_users', as: 'specific_company_users'
  match 'create_company/:parent_company_id' => 'companies#create', as: 'create_company'
  match 'return_company_users/:company_id' => 'companies#return_company_users', as: 'return_company_users'
  
  resource :contact_emails
  resource :contact_phones
  
  resources :groups, except: :show
  
  match 'employee_post/:id' => 'employee_posts#destroy', as: 'employee_post', via: :delete

  controller :passwords do
    get 'request_password' => :request_password
    put 'password' => :set_token
    post 'password' => :create
  end
  match 'password/:token' => 'passwords#new', as: 'password_token'
  
  controller :settings do
    get 'settings' => :index
  end
  
  controller :sessions do
    get 'sign_in' => :new
    post 'sign_in' => :create
    delete 'sign_out' => :destroy
  end

  resources :users
  controller :users do
    put 'forward_roles' => :forward_roles_update
    get 'change_password' => :change_password
    put 'change_password' => :change_password_update
  end
  match 'activate_user/:code' => 'users#activate', as: 'activate_user'
  match 'forward_roles' => 'users#forward_roles', as: 'forward_roles'
  
  root to: "sessions#new"
end

app/models/backoffice_core/ability.rb
#!/bin/env ruby
# encoding: utf-8

module BackofficeCore
  class Ability
    include CanCan::Ability
    
    def initialize(user)
      if user.role? :manage_users
        can :read, User
        can :update, User
      end
      if user.role? :delete_users
        can :destroy, User
      end
      if user.role? :company_founder
        can :manage, Company, id: user.company.tree.ids
      end

      # admins can update group      
      can [:update, :edit], Group, admins: { id: user.id }      
      can :destroy, Group, admin_destroy_group: true, admins: { id: user.id }
      can :add_members, Group, admin_add_user: true, admins: { id: user.id }
      can :remove_members, Group, admin_remove_user: true, admins: { id: user.id }
      # group main admin can do everything
      can [:manage, :add_members, :remove_members, :add_admins, :remove_admins], Group, main_admin_user_id: user.id      
#      can :add_members, Group, main_admin_user_id: user.id
#      can :remove_members, Group, main_admin_user_id: user.id
#      can :remove_admins, Group, main_admin_user_id: user.id
#      can :add_admins, Group, main_admin_user_id: user.id
    end
  end
end

app/models/backoffice_core/city.rb
module BackofficeCore
  class City < ActiveRecord::Base
    attr_accessible :title
  end
end

app/models/backoffice_core/company.rb
#!/bin/env ruby
# encoding: utf-8

module BackofficeCore
  class Company < ActiveRecord::Base
    attr_accessible :id, :parent_company_id, :title, :ico, :dic,
                    :street, :orientation_number, :house_number, :city, :postal_code,
                    :phone, :cell_phone, :fax, :email, :www,
                    :fb, :icq, :skype, :description, :company_type_id,
                    :country_id, :parent_company_id
                    
    validates_presence_of :title, on: :update, message: "nesmí být prázdný"
    
    belongs_to :company_type
    belongs_to :country
    belongs_to :parent_company, class_name: "Company", foreign_key: "parent_company_id"
    has_many :children_companies, class_name: "Company", foreign_key: "parent_company_id"
    has_many :company_detail_types
    has_many :company_details
    has_many :employee_posts
    has_many :users
    has_one :group, foreign_key: "automatic_company_id"

    # counts bill for one company    
    def bill_for_all_company_licenses
      bill = 0
      
      License.all.each do |l|
        bill += self.count_company_licenses(l) * l.price
      end
      bill
    end
    
    # counts complete bill for top company and subcompanies
    def bill_for_whole_company_licenses
      bill = 0
      
      self.tree.one_level_array.each do |c|
        bill += c.bill_for_all_company_licenses
      end
      bill
    end
    
    def branch_office_title
      if self.is_top_parent?
        "Mateřská kancelář"
      else
        self.title
      end
    end    
    
    def children_companies_hash(parent_company)
      hash = {}
      
      if parent_company.children_companies.any?
        parent_company.children_companies.each do |child|
          hash[child.to_s] = self.children_companies_hash(child)
        end
      end
      hash
    end
    
    def count_all_subcompanies
      self.tree.one_level_array.size - 1
    end

    def count_company_licenses(license)
      counter = 0
      
      self.users.each do |u|
        counter += 1 if u.license == license
      end
      counter
    end
    
    def count_indirect_subcompanies
      self.count_all_subcompanies - self.children_companies.count
    end
    
    def count_paid_users_licenses
      licenses_count = 0
      
      self.users.each do |u|
        licenses_count += 1 if u.license.price > 0
      end
      licenses_count
    end

    def count_whole_company_users
      count = 0
      
      self.tree.one_level_array.each do |i|
        count += i.users.count
      end
      count
    end
    
    def count_company_founders
      count = 0
      
      self.users.each do |u|
        count += 1 if u.role?('company_founder')
      end
      count
    end

    def is_child_of?(company)
      ct = CompanyTree.new(company)        
      ct.ids.include? self.id
    end
    
    def is_top_parent?
      self.parent_company.blank?
    end
    
    def primary_post
      self.employee_posts.where("primary_post = 1").first || self.top_parent_company.employee_posts.where("primary_post = 1").first || self.top_parent_company.employee_posts.first
    end
    
    # company_details: key, value = company_detail.id, detail_value
    # recursive: array of company_detail.ids (from first param)
    #            that should be saved in all subcompanies
    def save_existing_company_details(company_details, recursive)
      company_details.each do |key, value|
        # if recursive, pass to all subcompanies
        if recursive.is_a? Hash and recursive.key? key
          detail_title = self.company_details.find(key).company_detail_type.title
          
          self.tree.one_level_array.each do |company|
            cdt = company.company_detail_types.find_by_title(detail_title)
            
            # if chosen detail type doesn't exist, create it and create it's value
            if cdt.blank?
              cdt = company.company_detail_types.create(title: detail_title)
              cdt.company_details.create(detail_value: value, company_id: company.id)
            else # cdt existuje, smazeme dosavadni cd a nastavime nove
              cd = company.company_details.where(company_detail_type_id: cdt.id).first
              
              if cd.blank?
                cdt.company_details.create(detail_value: value, company_id: company.id)
              else
                cd.update_attribute('detail_value', value)
              end
            end
          end
        else
          cd = self.company_details.find(key)
          cd.update_attribute('detail_value', value)
        end
      end
    end

    # saves existing details only in chosen company, not into subcompanies
    def save_existing_company_details_only_node(company_details)
      company_details.each do |key, value|
        cd = self.company_details.find(key)
        cd.update_attribute('detail_value', value)
      end
    end

    # nepropise se novy detail do podpobocek
    def save_new_company_details(new_company_details, recursive)
      x = {}
      new_company_details.each do |key, detail|
          cdt = self.company_detail_types.find_by_title(detail[:title])

          if cdt.blank?
            cdt = self.company_detail_types.create(title: detail[:title])
          end
          
          cd = self.company_details.create(company_detail_type_id: cdt.id, detail_value: detail[:detail_value])
          
          if recursive.is_a? Hash and recursive.key? key
            self.save_existing_company_details({ cd.id => cd.detail_value },
                                               { cd.id => "1" })
          end
          
      end
    end
    
    def save_params_to_all_subcompanies(params, company_params)
      if params.present? and params.any? and self.tree.one_level_array.any?
        params.each do |param, value|
          self.tree.one_level_array.each do |company|
            # rozdil mezi company[:title] a company['title'] - ten druhy vytvarim, potrebuju ale ten druhy
            raise ActiveRecord::RecordInvalid unless company.update_attribute(param, company_params[param])
          end
        end
      end
    end
    
    def to_s
      self.title
    end

    def top_parent_company
      if self.parent_company.blank?
        self
      else
        self.find_top_parent_company(self.parent_company)      
      end
    end
    
    def tree
      CompanyTree.new(self)
    end
    
    def whole_company_users
      users = []
      
      self.tree.one_level_array.each do |company|
        company.users.each do |u|
          users << u
        end
      end
      users
    end
    
    def whole_company_users_count_by_posts
      posts = []
      
      self.employee_posts.each do |post|
        posts << [post.title, post.users.count]
      end
      posts
    end
    
    def manage_automatic_group(main_admin_user)
      if self.group.blank?
        automatic_group = Group.create(title: self.title, 
                            description: 'automatická skupina společnosti', 
                            main_admin_user_id: main_admin_user.id.to_s, 
                            automatic: 1, 
                            automatic_company_id: self.id.to_s, 
                            created_at: Time.now)
      else
        automatic_group = self.group
        automatic_group.update_attribute('title', self.title)
      end
      automatic_group.save!
    end   

    protected

    def find_top_parent_company(company)
      if company.parent_company.present?
        self.find_top_parent_company(company.parent_company)
      else
        company
      end
    end 
  end
end

app/models/backoffice_core/company_detail.rb
module BackofficeCore
  class CompanyDetail < ActiveRecord::Base
    attr_accessible :id, :company_detail_type_id, :company_id, :detail_value
    
    validates_presence_of :company_detail_type_id
    
    belongs_to :company
    belongs_to :company_detail_type
    
    def to_s
      self.id.to_s + ': ' + self.detail_value
    end
  end
end

app/models/backoffice_core/company_detail_type.rb
module BackofficeCore
  class CompanyDetailType < ActiveRecord::Base
    attr_accessible :title, :company_id, :id
    
    validates_presence_of :title
    validates_uniqueness_of :title, scope: :company_id
    
    belongs_to :company
    has_many :company_details
  end
end

app/models/backoffice_core/company_tree.rb
#!/bin/env ruby
# encoding: utf-8

module BackofficeCore
  class CompanyTree
    include ActiveModel::Validations
    include ActiveModel::Conversion
    extend ActiveModel::Naming
    
    attr_accessor :company, :ids, :one_level_array
    
    def initialize(company)
      if company.is_a? Company
        self.company = company
      elsif company.is_a? Integer
        self.company = Company.find(company)
      end
      self.one_level_array = []
      self.one_level_array << self.company
      self.ids = []
      self.ids << self.company.id
      self.list(self.company)
    end
    
    def list(parent_company)
      if parent_company.children_companies.any?        
        parent_company.children_companies.each do |child|
          self.one_level_array << child
          self.ids << child.id
          self.list(child)
        end
      end
    end
  end
end

app/models/backoffice_core/company_type.rb
module BackofficeCore
  class CompanyType < ActiveRecord::Base
    attr_accessible :title
    
    has_many :companies
  end
end

app/models/backoffice_core/contact_email.rb
#!/bin/env ruby
# encoding: utf-8

module BackofficeCore
  class ContactEmail < ActiveRecord::Base
    attr_accessible :id, :email, :email_usage, :note, :primary_email, :user_id
    
    validates_uniqueness_of :email, scope: :user_id, message: 'Tento email již je v databázi uložen.'
    
    belongs_to :user
    
    def to_s
      self.email
    end
  end
end

app/models/backoffice_core/contact_phone.rb
#!/bin/env ruby
# encoding: utf-8

module BackofficeCore
  class ContactPhone < ActiveRecord::Base
    attr_accessible :phone, :phone_type, :phone_usage, :note, :primary_phone, :user_id
    
    validates_uniqueness_of :phone, scope: :user_id, message: 'Tento telefon již je v databázi uložen'
    
    belongs_to :user
    
    def to_s
      self.phone
    end
  end
end

app/models/backoffice_core/country.rb
module BackofficeCore
  class Country < ActiveRecord::Base
    attr_accessible :title
    
    has_many :users
    has_many :companies
  end
end

app/models/backoffice_core/employee_post.rb
module BackofficeCore
  class EmployeePost < ActiveRecord::Base
    attr_accessible :company_id, :title, :primary_post
    
    has_many :users
    belongs_to :company
  end
end

app/models/backoffice_core/language.rb
module BackofficeCore
  class Language < ActiveRecord::Base
    attr_accessible :title
    
    has_and_belongs_to_many :users, join_table: :backoffice_core_languages_users
  end
end

app/models/backoffice_core/license.rb
module BackofficeCore
  class License < ActiveRecord::Base
    attr_accessible :id, :duration, :price, :title, :license_type
    
    has_many :users
    has_and_belongs_to_many :roles, join_table: :backoffice_core_licenses_roles
    
    def to_s
      '<License: ' + self.license_type + ' (license_id: ' + self.id.to_s + ')>'
    end
    
    def paid_licenses
      self.where("price > 0")
    end
  end
end

app/models/backoffice_core/log.rb
module BackofficeCore
  class Log < ActiveRecord::Base
    attr_accessible :description, :title, :user_id, :created_at
    
    belongs_to :user
    
    def to_s
      self.created_at.strftime("%d. %-m. %Y %k:%M:%S").to_s + ' ' + title
    end
  end
end

app/models/backoffice_core/nationality.rb
module BackofficeCore
  class Nationality < ActiveRecord::Base
    attr_accessible :title
    
    has_many :users
  end
end

app/models/backoffice_core/role.rb
module BackofficeCore
  class Role < ActiveRecord::Base
    attr_accessible :id, :name, :role_type
    attr_accessible :license_ids
    
    has_and_belongs_to_many :users, join_table: :backoffice_core_roles_users
    has_and_belongs_to_many :licenses, join_table: :backoffice_core_licenses_roles
    # k dane roli musi mit vyplnene urcite udaje
  end
end

app/models/backoffice_core/user_registration.rb
module BackofficeCore
  class UserRegistration < ActiveRecord::Base
    attr_accessible :id, :title
    
    has_many :users
  end
end

app/controllers/backoffice_core/application_controller.rb
#!/bin/env ruby
# encoding: utf-8

module BackofficeCore
  class ApplicationController < ActionController::Base
    before_filter :current_user, :authorize, :set_mailer_host

    rescue_from CanCan::AccessDenied do |exception|
      flash[:error] = "Nemáte oprávnění."
      redirect_to :back
    end
    
    protected
  
    def authorize
      unless User.find_by_id(session[:user_id])
        redirect_to sign_in_url, alert: "Prosím přihlašte se. Pokud nemáte uživatelský účet, zaregistrujte se."
      end
    end
    
    # workaround for use CanCan in engine
    def current_ability
      BackofficeCore::Ability.new(current_user)
    end
    
    def current_user
      if session[:user_id]
        @current_user = User.find(session[:user_id])
      else
        @current_user = User.new # have to create new empty object
      end
    end
    
    def set_mailer_host
      ActionMailer::Base.default_url_options = { host: request.host_with_port }
    end
  end
end

app/views/backoffice_core/users/_add_contact_emails.html.erb
<div id="add_contact_emails" class="modal_window">
  <%= render partial: '/backoffice_core/contact_emails/new' %>
</div>

app/views/backoffice_core/users/_add_contact_phones.html.erb
<div id="add_contact_phones" class="modal_window">
  <%= render partial: '/backoffice_core/contact_phones/new' %>
</div>

app/views/backoffice_core/users/_show_user.html.erb
<div id="user_profile">
  <div class="w300 f-left">
    <h3><%= raw @user.degree_before + '&nbsp;' if @user.show_degree_before.present? %>
        <%= @user.whole_name %>
        <%= raw '&nbsp;' + @user.degree_after if @user.show_degree_after %></h3>
    <% if @user.show_evidence_number %><p><%= @user.evidence_number %></p><% end %>
    <p><%= @user.employee_post.title + ' ' if @user.employee_post.present? %><%= @user.company.title if @user.company.present? %></p>
    <p><%= @user.primary_contact_phone %></p>
    <p><%= @user.email %></p>
    <hr>
    <p><strong>V systému od:</strong>&nbsp;<%= @user.created_at.strftime("%d. %-m. %Y") %></p>
    <hr>
    <% if @user.company.present? %>
      <% if @user.show_company %><p><strong>Společnost:</strong>&nbsp;<%= @user.company.title %></p><% end %>
      <% if @user.show_branch_office %><p><strong>Pobočka:</strong>&nbsp;<%= @user.company.branch_office_title %></p><% end %>
      <% if @user.show_address and (@user.company.street or @user.company.city) %>
        <p class="f-left"><strong>Adresa:</strong>&nbsp;</p>
        <div class="f-left">
          <% if @user.company.street %>
            <%= @user.company.street %> 
              <%= @user.company.orientation_number + ' /' if @user.company.orientation_number.present? %>
              <%= @user.company.house_number if @user.company.house_number.present? %><br>
          <% end %>
          <%= raw @user.company.city + '<br>' if @user.company.city.present? %>
          <%= @user.company.postal_code if @user.company.postal_code.present? %>
        </div>
        <div class="cleaner"></div>
      <% end %>
      <p><strong>E-mail:</strong> <%= @user.company.email %></p>
      <p><strong>Tel.:</strong> <%= @user.company.phone %></p>
    <% end %>
  </div>

  <div class="f-left w300 mt30 ml15">
    <% if @user.show_motto and @user.motto.present? %>
      <p><strong>Motto</strong><br>
      <%= @user.motto %></p>
    <% end %>
    <% if @user.show_description and  @user.description.present? %>
      <p><strong>Popis</strong><br>
      <%= @user.description %></p>
    <% end %>
  </div>
  <div class="cleaner"></div>
</div>

app/views/backoffice_core/users/change_password.html.erb
<h1>Změna hesla</h1>
<%= render partial: '/backoffice_core/flash_messages' %>

<%= form_for @current_user, url: change_password_path, method: :put do |f| %>
  <%= f.label :password, 'Heslo' %>:
  <%= f.password_field :password, id: 'user_password' %><br><br>
  
  <%= f.label :password_confirmation, 'Heslo znovu' %>:
  <%= f.password_field :password_confirmation, id: 'user_password_confirmation' %><br><br>
  
  <%= f.submit 'Uložit nové heslo' %>  
<% end %>

app/views/backoffice_core/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/backoffice_core/users/create.html.erb</p>

app/views/backoffice_core/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/backoffice_core/users/destroy.html.erb</p>

app/views/backoffice_core/users/edit.html.erb
<h1>Profil uživatele</h1>
<%= render partial: '/backoffice_core/flash_messages' %>

<%= form_for @user, method: :put do |f| %>
  <% if @user.errors.any? %>
    <p class="error">Chyba při uložení uživatele.</p>
  <% end %>
  
  <%= f.submit 'Uložit', class: 'f-right' %>
  <br><br>
  <div class="cleaner"></div>
  
  <div class="f-left w290 mr5">
    <fieldset>
      <legend>Uživatel</legend>      
      <%= f.label :evidence_number, 'Ev. číslo:' %>
      <% if @user.errors[:evidence_number].any? %>
        <p><%= error_message_on @user, :evidence_number %></p>
        <%= f.text_field :evidence_number, class: 'error' %>
      <% else %>
        <%= f.text_field :evidence_number %>
      <% end %>
      <br>
      <!-- EMPLOYEE POSTS ONLY FOR COMPANY USER -->
      <% if @user.user_registration.id == 2 %>
        <%= f.label :employee_post_id, 'Zařazení:' %>
        <%= f.select(:employee_post_id, options_for_select(@employee_posts, @user.employee_post_id), blank: true) %>
        <br>
      <% end %>
      <%= f.label :degree_before, 'Titul před:' %>
      <%= f.text_field :degree_before %>
      <br>
      <%= f.label :name, 'Jméno:' %>
      <%= f.text_field :name %>
      <br>
      <%= f.label :surname, 'Příjmení:' %>
      <%= f.text_field :surname %>
      <br>
      <%= f.label :degree_after, 'Titul za:' %>
      <%= f.text_field :degree_after %>
    </fieldset>
    
    <fieldset>
      <legend>Adresa</legend>      
      <%= f.label :city, 'Město:' %>
      <%= f.text_field :city, class: 'city_completion' %>
      <br>
      <%= f.label :street, 'Ulice:' %>
      <%= f.text_field :street %>
      <br>
      <%= f.label :house_number, 'č.p.:' %>
      <%= f.text_field :house_number, class: 'w50' %>
      
      <%= f.label :orientation_number, 'č.o.:' %>
      <%= f.text_field :orientation_number, class: 'w50' %>
      <br>
      <%= f.label :postal_code, 'PSČ:' %>
      <%= f.text_field :postal_code %>
      <br>
      <%= f.label :country_id, 'Země:' %>
      <%= f.select(:country_id, options_for_select(@countries, @user.country_id)) %>
      <br>
      <%= f.label :nationality_id, 'Národnost:' %>
      <%= f.select(:nationality_id, options_for_select(@nationalities, @user.nationality_id)) %>
      <br>
      <%= f.label :language_id, 'Jazyky:' %>
      <%= f.collection_select 'language_ids', @languages, :id, :title, { include_blank: false }, { multiple: true, size: 3, name: 'user[language_ids][]' } %>
    </fieldset>
    
    <fieldset>
      <legend>Data</legend>
      <%= f.label :birth_date, 'Datum narození:' %>
      <%= f.text_field :birth_date, class: 'w150 datepicker' %>
      <br>
      <%= f.label :ico, 'IČO:' %>
      <%= f.text_field :ico %>
      <br>
      <%= f.label :dic, 'DIČ:' %>
      <%= f.text_field :dic %>
    </fieldset>
  </div>
  <div class="f-left w290 mr5">
    <fieldset>
      <legend>Kontakty</legend>
      <%= f.label :contact_phones, 'Telefony:', class: 'f-left' %>
      <a onclick="openMyModal('#add_contact_phones'); return false;" class="active_link f-right">Přidat</a>
      <div class="cleaner"></div>
      <%= select_tag "", options_for_select(@contact_phones), multiple: true, size: 3, class: 'w270', id: 'add_contact_phones_select_box' %>
      <br><br>
      <%= f.label :contact_phones, 'Emaily:', class: 'f-left' %>
      <a onclick="openMyModal('#add_contact_emails'); return false;" class="active_link f-right">Přidat</a>
      <div class="cleaner"></div>
      <%= select_tag "", options_for_select(@contact_emails), multiple: true, size: 3, class: 'w270', id: 'add_contact_emails_select_box' %>
      <br><br>
      <%= f.label :www, 'WWW:' %>
      <%= f.text_field :www %>
      <br>
      <%= f.label :skype, 'Skype:' %>
      <%= f.text_field :skype %>
      <br>
      <%= f.label :icq, 'ICQ:' %>
      <%= f.text_field :icq %>
      <br>
      <%= f.label :twitter, 'Twitter:' %>
      <%= f.text_field :twitter %>
      <br>
      <%= f.label :fb, 'Facebook:' %>
      <%= f.text_field :fb %>
      <br>      
    </fieldset>
    
    <fieldset>
      <legend>Kontakty</legend>
      <%= f.label :has_wife, 'Manželka:' %>&nbsp;<%= f.check_box :has_wife %><br>
      <%= f.label :has_partner, 'Partnerka:' %>&nbsp;<%= f.check_box :has_partner %><br>
      <%= f.label :has_children, 'Děti:' %>&nbsp;<%= f.check_box :has_children %>&nbsp;
      <%= f.label :children_count, 'Kolik:' %>&nbsp;<%= f.text_field :children_count, class: 'w50' %><br>
      <%= f.label :has_pet, 'Zvíře:' %>&nbsp;<%= f.check_box :has_pet %>&nbsp;
      <%= f.label :pet_race, 'Jaké:' %>&nbsp;<%= f.text_field :pet_race, class: 'w50' %>
    </fieldset>
  </div>
  <div class="f-left w595 mr5">
    <%= f.label :motto, 'Motto:' %><br>
    <%= f.text_area :motto, class: 'w595 h100' %>
    <br><br>
    <%= f.label :description, 'Popis:' %>
    <%= f.text_area :description, class: 'w595 h200' %>
    <br><br>
    <%= f.label :logs, 'Události uživatele:' %>
    <%= select_tag "user_log", options_for_select(@logs), multiple: true, size: 12, class: 'w595'%>
  </div>
  <div class="cleaner"></div>
  <div class="w300">
    <h3>Zobrazit v profilu</h3>
    <div class="chk"><%= f.label :show_degree_before, 'Titul před' %>&nbsp;<%= f.check_box :show_degree_before %></div>
    <div class="chk"><%= f.label :show_degree_after, 'Titul za' %>&nbsp;<%= f.check_box :show_degree_after %></div>
    <div class="chk"><%= f.label :show_evidence_number, 'Ev. číslo' %>&nbsp;<%= f.check_box :show_evidence_number %></div>
    <div class="chk"><%= f.label :show_company, 'Společnost' %>&nbsp;<%= f.check_box :show_company %></div>
    <div class="chk"><%= f.label :show_branch_office, 'Pobočka' %>&nbsp;<%= f.check_box :show_branch_office %></div>
    <div class="chk"><%= f.label :show_address, 'Adresa' %>&nbsp;<%= f.check_box :show_address %></div>
    <div class="chk"><%= f.label :show_motto, 'Motto' %>&nbsp;<%= f.check_box :show_motto %></div>
    <div class="chk"><%= f.label :show_description, 'Popis' %>&nbsp;<%= f.check_box :show_description %></div>
    <div class="cleaner"></div>
  </div>
  <br>
<% end %>

<%= render partial: '/backoffice_core/users/show_user' %>

app/views/backoffice_core/users/forward_roles.html.erb
<h1>Nastavení</h1>
<%= render partial: '/backoffice_core/flash_messages' %>

<div id="left">
  <%= render partial: '/backoffice_core/menu_settings' %>
</div>
<div id="right">
  <div class="ml15">
  <h3>Předat práva kolegovi</h3>

  <%= form_tag forward_roles_path, method: :put do -%>
    <%= label_tag 'selected_user_id', 'Vyberte kolegu:' %>
    <%= select_tag 'selected_user_id', options_for_select(@users) %>
    <%= submit_tag 'Předat' %>
  <% end -%>
</div>
<div class="cleaner"></div>

app/views/backoffice_core/users/index.html.erb
<h1>Uživatelé</h1>
<%= render partial: '/backoffice_core/flash_messages' %>

app/views/backoffice_core/users/new.html.erb
<h2>Registrace nového uživatele</h2>
  <% if @user.errors.any? %>
    <p class="error">Chyba při registraci.</p>
  <% end %>

<%= form_for @user, url: users_url, method: :post do |form| %>
  <%= form.label :email, 'Email:' %>
  <% if @user.errors[:email].any? %>
    <%= error_message_on @user, :email %>
  <% end %>
  <%= form.text_field :email, type: 'email', id: 'user_email' %>
  <br><br>
  
  <%= form.label :password, 'Heslo:' %>
  <% if @user.errors[:password].any? %>
    <%= error_message_on @user, :password %>
  <% end %>
  <%= form.password_field :password, id: 'user_password' %>
  <br><br>
  
  <%= form.label :password_confirmation, 'Heslo znovu:' %>
  <% if @user.errors[:password_confirmation].any? %>
    <%= error_message_on @user, :password_confirmation %>
  <% end %>
  <%= form.password_field :password_confirmation, id: 'user_password_confirmation' %>
  <br><br>
  
  <%= form.label :user_registration_id, 'Typ registrace:' %>
  <% if @user.errors[:user_registration_id].any? %>
    <%= error_message_on @user, :user_registration_id %>
  <% end %>
  <% @user_registrations.each_with_index do |ur, i| %>
    <% if i > 0 %>
      <%= form.radio_button :user_registration_id, ur[0], checked: true %>
    <% else %>
      <%= form.radio_button :user_registration_id, ur[0]  %>
    <% end %>
    <%= form.label "user_registration_id_#{ur[0]}", ur[1] %>
  <% end %>
  <br><br>
  <%= form.submit 'Zaregistrovat' %>
<% end %>

app/views/backoffice_core/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/backoffice_core/users/update.html.erb</p>