config/routes.rb
BackofficeCore::Engine.routes.draw do
  match 'select_cities/:city_title' => 'cities#select_cities', as: 'select_cities'
  
  resources :companies, only: [:show, :destroy]
  controller :companies do
    get 'company_structure' => :company_structure
    put 'company_structure' => :company_structure_update
    get 'company_details' => :company_details
    put 'company_details' => :company_details_update
    get 'company_employee_posts' => :company_employee_posts
    put 'company_employee_posts' => :company_employee_posts_update
    get 'company_users' => :company_users
    put 'company_users' => :company_users_update
    get 'company_finish' => :company_finish
    put 'company_finish' => :company_finish_update
  end
  match 'company_details/:company_id' => 'companies#company_details', as: 'specific_company_details'
  match 'company_users/:company_id' => 'companies#company_users', as: 'specific_company_users'
  match 'create_company/:parent_company_id' => 'companies#create', as: 'create_company'
  match 'return_company_users/:company_id' => 'companies#return_company_users', as: 'return_company_users'
  
  resource :contact_emails
  resource :contact_phones
  
  resources :groups, except: :show
  
  match 'employee_post/:id' => 'employee_posts#destroy', as: 'employee_post', via: :delete

  controller :passwords do
    get 'request_password' => :request_password
    put 'password' => :set_token
    post 'password' => :create
  end
  match 'password/:token' => 'passwords#new', as: 'password_token'
  
  controller :settings do
    get 'settings' => :index
  end
  
  controller :sessions do
    get 'sign_in' => :new
    post 'sign_in' => :create
    delete 'sign_out' => :destroy
  end

  resources :users
  controller :users do
    put 'forward_roles' => :forward_roles_update
    get 'change_password' => :change_password
    put 'change_password' => :change_password_update
  end
  match 'activate_user/:code' => 'users#activate', as: 'activate_user'
  match 'forward_roles' => 'users#forward_roles', as: 'forward_roles'
  
  root to: "sessions#new"
end

app/models/backoffice_core/ability.rb
#!/bin/env ruby
# encoding: utf-8

module BackofficeCore
  class Ability
    include CanCan::Ability
    
    def initialize(user)
      if user.role? :manage_users
        can :read, User
        can :update, User
      end
      if user.role? :delete_users
        can :destroy, User
      end
      if user.role? :company_founder
        can :manage, Company, id: user.company.tree.ids
      end

      # admins can update group      
      can [:update, :edit], Group, admins: { id: user.id }      
      can :destroy, Group, admin_destroy_group: true, admins: { id: user.id }
      can :add_members, Group, admin_add_user: true, admins: { id: user.id }
      can :remove_members, Group, admin_remove_user: true, admins: { id: user.id }
      # group main admin can do everything
      can [:manage, :add_members, :remove_members, :add_admins, :remove_admins], Group, main_admin_user_id: user.id      
#      can :add_members, Group, main_admin_user_id: user.id
#      can :remove_members, Group, main_admin_user_id: user.id
#      can :remove_admins, Group, main_admin_user_id: user.id
#      can :add_admins, Group, main_admin_user_id: user.id
    end
  end
end

app/models/backoffice_core/city.rb
module BackofficeCore
  class City < ActiveRecord::Base
    attr_accessible :title
  end
end

app/models/backoffice_core/company.rb
#!/bin/env ruby
# encoding: utf-8

module BackofficeCore
  class Company < ActiveRecord::Base
    attr_accessible :id, :parent_company_id, :title, :ico, :dic,
                    :street, :orientation_number, :house_number, :city, :postal_code,
                    :phone, :cell_phone, :fax, :email, :www,
                    :fb, :icq, :skype, :description, :company_type_id,
                    :country_id, :parent_company_id
                    
    validates_presence_of :title, on: :update, message: "nesmí být prázdný"
    
    belongs_to :company_type
    belongs_to :country
    belongs_to :parent_company, class_name: "Company", foreign_key: "parent_company_id"
    has_many :children_companies, class_name: "Company", foreign_key: "parent_company_id"
    has_many :company_detail_types
    has_many :company_details
    has_many :employee_posts
    has_many :users
    has_one :group, foreign_key: "automatic_company_id"

    # counts bill for one company    
    def bill_for_all_company_licenses
      bill = 0
      
      License.all.each do |l|
        bill += self.count_company_licenses(l) * l.price
      end
      bill
    end
    
    # counts complete bill for top company and subcompanies
    def bill_for_whole_company_licenses
      bill = 0
      
      self.tree.one_level_array.each do |c|
        bill += c.bill_for_all_company_licenses
      end
      bill
    end
    
    def branch_office_title
      if self.is_top_parent?
        "Mateřská kancelář"
      else
        self.title
      end
    end    
    
    def children_companies_hash(parent_company)
      hash = {}
      
      if parent_company.children_companies.any?
        parent_company.children_companies.each do |child|
          hash[child.to_s] = self.children_companies_hash(child)
        end
      end
      hash
    end
    
    def count_all_subcompanies
      self.tree.one_level_array.size - 1
    end

    def count_company_licenses(license)
      counter = 0
      
      self.users.each do |u|
        counter += 1 if u.license == license
      end
      counter
    end
    
    def count_indirect_subcompanies
      self.count_all_subcompanies - self.children_companies.count
    end
    
    def count_paid_users_licenses
      licenses_count = 0
      
      self.users.each do |u|
        licenses_count += 1 if u.license.price > 0
      end
      licenses_count
    end

    def count_whole_company_users
      count = 0
      
      self.tree.one_level_array.each do |i|
        count += i.users.count
      end
      count
    end
    
    def count_company_founders
      count = 0
      
      self.users.each do |u|
        count += 1 if u.role?('company_founder')
      end
      count
    end

    def is_child_of?(company)
      ct = CompanyTree.new(company)        
      ct.ids.include? self.id
    end
    
    def is_top_parent?
      self.parent_company.blank?
    end
    
    def primary_post
      self.employee_posts.where("primary_post = 1").first || self.top_parent_company.employee_posts.where("primary_post = 1").first || self.top_parent_company.employee_posts.first
    end
    
    # company_details: key, value = company_detail.id, detail_value
    # recursive: array of company_detail.ids (from first param)
    #            that should be saved in all subcompanies
    def save_existing_company_details(company_details, recursive)
      company_details.each do |key, value|
        # if recursive, pass to all subcompanies
        if recursive.is_a? Hash and recursive.key? key
          detail_title = self.company_details.find(key).company_detail_type.title
          
          self.tree.one_level_array.each do |company|
            cdt = company.company_detail_types.find_by_title(detail_title)
            
            # if chosen detail type doesn't exist, create it and create it's value
            if cdt.blank?
              cdt = company.company_detail_types.create(title: detail_title)
              cdt.company_details.create(detail_value: value, company_id: company.id)
            else # cdt existuje, smazeme dosavadni cd a nastavime nove
              cd = company.company_details.where(company_detail_type_id: cdt.id).first
              
              if cd.blank?
                cdt.company_details.create(detail_value: value, company_id: company.id)
              else
                cd.update_attribute('detail_value', value)
              end
            end
          end
        else
          cd = self.company_details.find(key)
          cd.update_attribute('detail_value', value)
        end
      end
    end

    # saves existing details only in chosen company, not into subcompanies
    def save_existing_company_details_only_node(company_details)
      company_details.each do |key, value|
        cd = self.company_details.find(key)
        cd.update_attribute('detail_value', value)
      end
    end

    # nepropise se novy detail do podpobocek
    def save_new_company_details(new_company_details, recursive)
      x = {}
      new_company_details.each do |key, detail|
          cdt = self.company_detail_types.find_by_title(detail[:title])

          if cdt.blank?
            cdt = self.company_detail_types.create(title: detail[:title])
          end
          
          cd = self.company_details.create(company_detail_type_id: cdt.id, detail_value: detail[:detail_value])
          
          if recursive.is_a? Hash and recursive.key? key
            self.save_existing_company_details({ cd.id => cd.detail_value },
                                               { cd.id => "1" })
          end
          
      end
    end
    
    def save_params_to_all_subcompanies(params, company_params)
      if params.present? and params.any? and self.tree.one_level_array.any?
        params.each do |param, value|
          self.tree.one_level_array.each do |company|
            # rozdil mezi company[:title] a company['title'] - ten druhy vytvarim, potrebuju ale ten druhy
            raise ActiveRecord::RecordInvalid unless company.update_attribute(param, company_params[param])
          end
        end
      end
    end
    
    def to_s
      self.title
    end

    def top_parent_company
      if self.parent_company.blank?
        self
      else
        self.find_top_parent_company(self.parent_company)      
      end
    end
    
    def tree
      CompanyTree.new(self)
    end
    
    def whole_company_users
      users = []
      
      self.tree.one_level_array.each do |company|
        company.users.each do |u|
          users << u
        end
      end
      users
    end
    
    def whole_company_users_count_by_posts
      posts = []
      
      self.employee_posts.each do |post|
        posts << [post.title, post.users.count]
      end
      posts
    end
    
    def manage_automatic_group(main_admin_user)
      if self.group.blank?
        automatic_group = Group.create(title: self.title, 
                            description: 'automatická skupina společnosti', 
                            main_admin_user_id: main_admin_user.id.to_s, 
                            automatic: 1, 
                            automatic_company_id: self.id.to_s, 
                            created_at: Time.now)
      else
        automatic_group = self.group
        automatic_group.update_attribute('title', self.title)
      end
      automatic_group.save!
    end   

    protected

    def find_top_parent_company(company)
      if company.parent_company.present?
        self.find_top_parent_company(company.parent_company)
      else
        company
      end
    end 
  end
end

app/models/backoffice_core/company_detail.rb
module BackofficeCore
  class CompanyDetail < ActiveRecord::Base
    attr_accessible :id, :company_detail_type_id, :company_id, :detail_value
    
    validates_presence_of :company_detail_type_id
    
    belongs_to :company
    belongs_to :company_detail_type
    
    def to_s
      self.id.to_s + ': ' + self.detail_value
    end
  end
end

app/models/backoffice_core/company_detail_type.rb
module BackofficeCore
  class CompanyDetailType < ActiveRecord::Base
    attr_accessible :title, :company_id, :id
    
    validates_presence_of :title
    validates_uniqueness_of :title, scope: :company_id
    
    belongs_to :company
    has_many :company_details
  end
end

app/models/backoffice_core/company_tree.rb
#!/bin/env ruby
# encoding: utf-8

module BackofficeCore
  class CompanyTree
    include ActiveModel::Validations
    include ActiveModel::Conversion
    extend ActiveModel::Naming
    
    attr_accessor :company, :ids, :one_level_array
    
    def initialize(company)
      if company.is_a? Company
        self.company = company
      elsif company.is_a? Integer
        self.company = Company.find(company)
      end
      self.one_level_array = []
      self.one_level_array << self.company
      self.ids = []
      self.ids << self.company.id
      self.list(self.company)
    end
    
    def list(parent_company)
      if parent_company.children_companies.any?        
        parent_company.children_companies.each do |child|
          self.one_level_array << child
          self.ids << child.id
          self.list(child)
        end
      end
    end
  end
end

app/models/backoffice_core/company_type.rb
module BackofficeCore
  class CompanyType < ActiveRecord::Base
    attr_accessible :title
    
    has_many :companies
  end
end

app/models/backoffice_core/contact_email.rb
#!/bin/env ruby
# encoding: utf-8

module BackofficeCore
  class ContactEmail < ActiveRecord::Base
    attr_accessible :id, :email, :email_usage, :note, :primary_email, :user_id
    
    validates_uniqueness_of :email, scope: :user_id, message: 'Tento email již je v databázi uložen.'
    
    belongs_to :user
    
    def to_s
      self.email
    end
  end
end

app/models/backoffice_core/contact_phone.rb
#!/bin/env ruby
# encoding: utf-8

module BackofficeCore
  class ContactPhone < ActiveRecord::Base
    attr_accessible :phone, :phone_type, :phone_usage, :note, :primary_phone, :user_id
    
    validates_uniqueness_of :phone, scope: :user_id, message: 'Tento telefon již je v databázi uložen'
    
    belongs_to :user
    
    def to_s
      self.phone
    end
  end
end

app/models/backoffice_core/country.rb
module BackofficeCore
  class Country < ActiveRecord::Base
    attr_accessible :title
    
    has_many :users
    has_many :companies
  end
end

app/models/backoffice_core/employee_post.rb
module BackofficeCore
  class EmployeePost < ActiveRecord::Base
    attr_accessible :company_id, :title, :primary_post
    
    has_many :users
    belongs_to :company
  end
end

app/models/backoffice_core/language.rb
module BackofficeCore
  class Language < ActiveRecord::Base
    attr_accessible :title
    
    has_and_belongs_to_many :users, join_table: :backoffice_core_languages_users
  end
end

app/models/backoffice_core/license.rb
module BackofficeCore
  class License < ActiveRecord::Base
    attr_accessible :id, :duration, :price, :title, :license_type
    
    has_many :users
    has_and_belongs_to_many :roles, join_table: :backoffice_core_licenses_roles
    
    def to_s
      '<License: ' + self.license_type + ' (license_id: ' + self.id.to_s + ')>'
    end
    
    def paid_licenses
      self.where("price > 0")
    end
  end
end

app/models/backoffice_core/log.rb
module BackofficeCore
  class Log < ActiveRecord::Base
    attr_accessible :description, :title, :user_id, :created_at
    
    belongs_to :user
    
    def to_s
      self.created_at.strftime("%d. %-m. %Y %k:%M:%S").to_s + ' ' + title
    end
  end
end

app/models/backoffice_core/nationality.rb
module BackofficeCore
  class Nationality < ActiveRecord::Base
    attr_accessible :title
    
    has_many :users
  end
end

app/models/backoffice_core/role.rb
module BackofficeCore
  class Role < ActiveRecord::Base
    attr_accessible :id, :name, :role_type
    attr_accessible :license_ids
    
    has_and_belongs_to_many :users, join_table: :backoffice_core_roles_users
    has_and_belongs_to_many :licenses, join_table: :backoffice_core_licenses_roles
    # k dane roli musi mit vyplnene urcite udaje
  end
end

app/models/backoffice_core/user_registration.rb
module BackofficeCore
  class UserRegistration < ActiveRecord::Base
    attr_accessible :id, :title
    
    has_many :users
  end
end

app/controllers/backoffice_core/application_controller.rb
#!/bin/env ruby
# encoding: utf-8

module BackofficeCore
  class ApplicationController < ActionController::Base
    before_filter :current_user, :authorize, :set_mailer_host

    rescue_from CanCan::AccessDenied do |exception|
      flash[:error] = "Nemáte oprávnění."
      redirect_to :back
    end
    
    protected
  
    def authorize
      unless User.find_by_id(session[:user_id])
        redirect_to sign_in_url, alert: "Prosím přihlašte se. Pokud nemáte uživatelský účet, zaregistrujte se."
      end
    end
    
    # workaround for use CanCan in engine
    def current_ability
      BackofficeCore::Ability.new(current_user)
    end
    
    def current_user
      if session[:user_id]
        @current_user = User.find(session[:user_id])
      else
        @current_user = User.new # have to create new empty object
      end
    end
    
    def set_mailer_host
      ActionMailer::Base.default_url_options = { host: request.host_with_port }
    end
  end
end

app/views/backoffice_core/companies/_children_company_input.html.erb
<% if children_company_input.present? %>
  <div class="ml30 input<%= children_company_input.id.to_s %>">
    <% if @error_fields.include? children_company_input.id.to_s %>
      <div class="field_with_errors">
    <% end %>
    <%= label_tag 'companies_' + children_company_input.id.to_s + '_title', 'Zadejte název pobočky:' %>
    <% if @error_fields.include? children_company_input.id.to_s %>
      </div>
      <div class="formError">nesmí být prázdný</div>
      <div class="field_with_errors">
    <% end %>    
    <%= text_field_tag 'companies[' + children_company_input.id.to_s + '][title]', children_company_input.title, onkeyup: 'javascript:forwardTitleToTreeNode(' + children_company_input.id.to_s + ');' %>
    <% if @error_fields.include? children_company_input.id.to_s %>
      </div>
    <% end %>
    <%= link_to 'Smazat', company_path(children_company_input), method: :delete, remote: true %>
    <%= hidden_field_tag 'companies[' + children_company_input.id.to_s + '][id]', children_company_input.id.to_s %>
    <% if children_company_input.children_companies.any? %>
      <%= render partial: '/backoffice_core/companies/children_company_input', collection: children_company_input.children_companies %>
    <% end %>
  </div>
<% end %>

app/views/backoffice_core/companies/_children_company_tree.html.erb
<% if children_company_tree.present? %>
    <li class="company_block" id="node<%= children_company_tree.id %>">
      <div>
        <h3><%= children_company_tree.title || "Zadejte název" %></h3>
        <p>Počet poboček: <span class="subcompanies_count"><%= children_company_tree.children_companies.count %></span> 
                          (<span class="all_subcompanies_count"><%= children_company_tree.count_all_subcompanies %></span>)</p>
        <%= link_to 'Přidat pobočku', 
                    { controller: 'companies', 
                      action: 'create', 
                      parent_company_id: children_company_tree.id, 
                      remote: true }, 
                    { class: 'create_company_link' } %>

      </div>
      <% if children_company_tree.children_companies.any? %>
        <ul>
          <%= render partial: '/backoffice_core/companies/children_company_tree', collection: children_company_tree.children_companies %>
        </ul>
      <% end %>
    </li>
<% end %>

app/views/backoffice_core/companies/company_details.html.erb
<%= render partial: '/backoffice_core/companies/company_process_header' %>

  <% if @company.errors.any? %>
    <p class="error">Chyba při uložení detailů společnosti.</p>
  <% end %>

  <%= form_tag company_details_path, method: :get do -%>
    <%= label_tag 'select_company_id', 'Popis společnosti' %>
    <%= select_tag 'select_company_id', options_for_select(@companies_for_select, @company.id), onchange: 'this.form.submit();' %>
    <br><br>
  <% end -%>
  <br>
  <br>
    
  <%= form_for @company, url: company_details_url, method: :put do |f| %>
    <%= link_to 'zpět na Strukturu společnosti', company_structure_url, class: 'f-left ml15' %>
    <%= f.submit 'Pokračovat', class: 'f-right' %>
    <%= hidden_field_tag 'selected_company_id', @company.id %>
    <div class="cleaner"></div>
    <br><br>

    <div class="w510 f-left ml15 mr15">
      <fieldset>
        <%= f.label :title, 'Název společnosti:' %>
        <%= f.text_field :title %>
        &nbsp;<%= check_box_tag 'recursive[title]' %>
        &nbsp;<%= label_tag 'recursive[title]', 'propasat do všech' %>
        <br>
        <%= f.label :ico, 'IČ:' %>
        <%= f.text_field :ico %>
        &nbsp;<%= check_box_tag 'recursive[ico]' %>
        &nbsp;<%= label_tag 'recursivep[ico]', 'propasat do všech' %>
        <br>
        <%= f.label :dic, 'DIČ:' %>
        <%= f.text_field :dic %>
        &nbsp;<%= check_box_tag 'recursive[dic]' %>
        &nbsp;<%= label_tag 'recursive[dic]', 'propasat do všech' %>
        <br>
        <%= f.label :street, 'Ulice:' %>
        <%= f.text_field :street %>
        &nbsp;<%= check_box_tag 'recursive[street]' %>
        &nbsp;<%= label_tag 'recursive[street]', 'propasat do všech' %>
        <br>
        <%= f.label :house_number, 'č.p.:' %>
        <%= f.text_field :house_number, class: 'w50' %>
        &nbsp;<%= check_box_tag 'recursive[house_number]' %>
        &nbsp;<%= label_tag 'recursive[house_number]', 'propasat do všech' %>
        <br>
        <%= f.label :orientation_number, 'č.o.:' %>
        <%= f.text_field :orientation_number, class: 'w50' %>
        &nbsp;<%= check_box_tag 'recursive[orientation_number]' %>
        &nbsp;<%= label_tag 'recursive[orientation_number]', 'propasat do všech' %>
        <br>
        <%= f.label :city, 'Město:' %>
        <%= f.text_field :city, class: 'city_completion' %>
        &nbsp;<%= check_box_tag 'recursive[city]' %>
        &nbsp;<%= label_tag 'recursive[city]', 'propasat do všech' %>
        <br>
        <%= f.label :postal_code, 'PSČ:' %>
        <%= f.text_field :postal_code, class: 'w100' %>
        &nbsp;<%= check_box_tag 'recursive[postal_code]' %>
        &nbsp;<%= label_tag 'recursive[postal_code]', 'propasat do všech' %>
        <br>
        <%= f.label :country_id, 'Země:' %>
        <%= f.select(:country_id, options_for_select(@countries, @company.country_id)) %>
        &nbsp;<%= check_box_tag 'recursive[country_id]' %>
        &nbsp;<%= label_tag 'recursive[country_id]', 'propasat do všech' %>
        <br>
      </fieldset>
      <br>
      <fieldset>
        <%= f.label :phone, 'Telefon:' %>
        <%= f.text_field :phone %>
        &nbsp;<%= check_box_tag 'recursive[phone]' %>
        &nbsp;<%= label_tag 'recursive[phone]', 'propasat do všech' %>
        <br>
        <%= f.label :cell_phone, 'Mobil:' %>
        <%= f.text_field :cell_phone %>
        &nbsp;<%= check_box_tag 'recursive[cell_phone]' %>
        &nbsp;<%= label_tag 'recursive[cell_phone]', 'propasat do všech' %>
        <br>
        <%= f.label :fax, 'Fax:' %>
        <%= f.text_field :fax %>
        &nbsp;<%= check_box_tag 'recursive[fax]' %>
        &nbsp;<%= label_tag 'recursive[fax]', 'propasat do všech' %>
        <br>
        <%= f.label :email, 'E-mail:' %>
        <%= f.text_field :email %>
        &nbsp;<%= check_box_tag 'recursive[email]' %>
        &nbsp;<%= label_tag 'recursive[email]', 'propasat do všech' %>
        <br>
        <%= f.label :www, 'WWW:' %>
        <%= f.text_field :www %>
        &nbsp;<%= check_box_tag 'recursive[www]' %>
        &nbsp;<%= label_tag 'recursive[www]', 'propasat do všech' %>
        <br>
        <%= f.label :fb, 'Facebook:' %>
        <%= f.text_field :fb %>
        &nbsp;<%= check_box_tag 'recursive[fb]' %>
        &nbsp;<%= label_tag 'recursive[fb]', 'propasat do všech' %>
        <br>
        <%= f.label :icq, 'ICQ:' %>
        <%= f.text_field :icq %>
        &nbsp;<%= check_box_tag 'recursive[icq]' %>
        &nbsp;<%= label_tag 'recursive[icq]', 'propasat do všech' %>
        <br>
        <%= f.label :skype, 'Skype:' %>
        <%= f.text_field :skype %>
        &nbsp;<%= check_box_tag 'recursive[skype]' %>
        &nbsp;<%= label_tag 'recursive[skype]', 'propasat do všech' %>
        <br>
        <% @company.company_details.each do |detail| %>
          <%= label_tag 'company_details[' + detail.id.to_s + ']', detail.company_detail_type.title + ':' %>
          <%= text_field_tag 'company_details[' + detail.id.to_s + ']', detail.detail_value %>
          <%= check_box_tag 'recursive_details[' + detail.id.to_s + ']' %>
          <%= label_tag 'recursive_details_' + detail.id.to_s, 'propsat do všech' %>
          <br>
        <% end %>
        <a href="javascript:add_company_detail(1);" class="t-right acd">přidat detail</a>  
      </fieldset>
      <br>
      <fieldset>
        <%= f.label :description, 'Popis společnosti:' %>
        <%= f.text_area :description, rows: 5, cols: 30 %>
        &nbsp;<%= check_box_tag 'description_recursive' %>
        &nbsp;<%= label_tag 'description_recursive', 'propasat do všech' %>
      </fieldset>
    </div>
    <div class="w475 f-left">
      <h2><%= @company.title %></h2>
      <%= raw '<p>IČ:' + @company.ico + '</p>' if @company.ico.present? %>
      <%= raw '<p>DIČ:' + @company.dic + '</p>' if @company.dic.present? %>
      <% if @company.street.present? %>
        <p><%= @company.street %>
           <%= ' ' + @company.orientation_number %>
           <%= ' / ' if @company.orientation_number.present? and @company.house_number.present? %>
           <%= @company.house_number %></p>
      <% end %>
      <%= raw '<p>' + @company.city + '</p>' if @company.city.present?  %>
      <%= raw '<p>' + @company.postal_code + '</p>' if @company.postal_code.present?  %>
      <%= raw '<p>' + @company.country.title + '</p>' if @company.country.present? %>
      <br>
      <hr>
      <br>
      <%= raw '<p>Telefon: ' + @company.phone + '</p>' if @company.phone.present?  %>
      <%= raw '<p>Mobil: ' + @company.cell_phone + '</p>' if @company.cell_phone.present? %>
      <%= raw '<p>Fax: ' + @company.fax + '</p>' if @company.fax.present? %>
      <%= raw '<p>E-mail: ' + @company.email + '</p>' if @company.email.present? %>
      <%= raw '<p>WWW: ' + @company.www + '</p>' if @company.www.present? %>
      <%= raw '<p>Facebook: ' + @company.fb + '</p>' if @company.fb.present? %>
      <%= raw '<p>ICQ: ' + @company.icq + '</p>' if @company.icq.present? %>
      <%= raw '<p>Skype: ' + @company.skype + '</p>' if @company.skype.present? %>  
      <% @company.company_details.each do |detail| %>
        <%= raw '<p>' + detail.company_detail_type.title + ': ' + detail.detail_value + '</p>' if detail.detail_value.present? %>
      <% end %>
      <br>
      <hr>
      <br>
      <%= raw '<p>' + @company.description + '</p>' if @company.description.present? %>
    </div>
    <div class="cleaner"></div>
  <% end %>
</div>
<div class="cleaner"></div>

app/views/backoffice_core/companies/company_employee_posts.html.erb
<%= render partial: '/backoffice_core/companies/company_process_header' %>

  <div class="ml15 mr15">
    <h2>Pojmenujte funkce ve vaší společnosti</h2>
    <%= form_tag(company_employee_posts_url, method: :put) do -%>
      <%= link_to 'zpět na Popis společnosti', company_details_url, class: 'f-left' %>
      <%= submit_tag 'Pokračovat', class: 'f-right' %>
      <div class="cleaner"></div>

      <fieldset class="w295 employee_posts_list">
        <% if @employee_posts.blank? %>
          <% (1..7).each do |n| %>
            <%= label_tag 'employee_posts[' + n.to_s + '][title]', n.to_s + '. -' %>
            <%= text_field_tag 'employee_posts[' + n.to_s + '][title]' %>
            <br><br>
          <% end %>
        <% else %>
          <% @employee_posts.each_with_index do |ep, n| %>
            <%= label_tag 'employee_posts[' + ep[1].to_s + '][title]', (n+1).to_s + '. -' %>
            <%= text_field_tag 'employee_posts[' + ep[1].to_s + '][title]', ep[0] %>
            <a href="<%= employee_post_url ep[1] %>" data-method="delete" data-confirm="opravdu?">Smaž</a>
            <br><br>
          <% end %>
        <% end %>
        <a href="javascript:add_employee_post(<%= @employee_posts.count + 1 %>)" class="t-right add_employee_post">Přidat další</a>
      </fieldset>
    <% end -%>
  </div>
</div>
<div class="cleaner"></div>